# Generated by Django 5.0.7 on 2024-07-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('farpost_id', models.IntegerField(verbose_name='ID в Farpost')),
                ('author', models.CharField(max_length=120, verbose_name='Автор')),
                ('views_count', models.IntegerField(verbose_name='Количество просмотров')),
                ('position', models.IntegerField(verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['position'],
            },
        ),
    ]
